/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRUlpaVlVbG9RR2tQOUFpLy8ydW4ydDJFZUJ1N0IyZlRTOGtHVkVKclIyST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZktnQnNvK0Z6c21aQnZWU2QrYXpuRm96T211UTd4UHdLTkJXajBKeUZWaz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJzT2UycGxnSFdiSytJWGlxUzBINlpYQm9GTGFHdkJRcmlpbUxtN0VlSEVBPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCNWpJSjhUeUV5MVFWNXZmVzhlamppUWQ1bFdvVzBycDduQW53M2t3dFdrPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IktMK0E2ZFdtdncwUW1iZlpQMTRwT1hQMG91YmtBUzAwSUpxa1RvcHhaMjg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImdUMlMwZzVIMFBhVThTNFVMeTZ1bC9rN05ZL1lvZVR3bk52azNrSE9lbW89In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUpwVHdrbGdBQWJESGozNnJlVWlQKzk2M2o3bnlKVG9vbU9IalMxMy9FOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWDNUKzhEU05Ic1hmb3IrS1B6enJTZ05MWW8yQno0elZzcno5QkNReXIwVT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InpEYVFlNm5jOXVoQVdybnVYUDdaREgzTFFPdEJjRG1DbFprNjZYeTJ3QlVxU0VGNGZGcXJCeW5lT1NMVHdtbk5nWDRZWEJCd1E3MWU5ditseUZlM0RRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjQxLCJhZHZTZWNyZXRLZXkiOiJKMjJIT2Jxd05iMkNLQWhTSnVZTGlnOEFLT2UxTTh3dEtCSFVCeCtXR0xzPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDEwNDI0NTY1OUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJDQjIxMTJBRTI2MkYzOTJERjc3QTExMDUxRkQyMDQxMSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzIyNzk1NjM0fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQxMDQyNDU2NTlAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMUMzQkQzMzY0NEZEQzM5M0YwMDkxRDc4M0Y3Q0U0ODgifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyMjc5NTYzOH0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0MTA0MjQ1NjU5QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkJGRTExMUU3M0UyRkY5OTZCREFCN0I3NzdEMkNFQUJDIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MjI3OTU2NjN9XSwibmV4dFByZUtleUlkIjozMiwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMyLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IkdTRmdzSVNGUTB1ZU5teWM2TlNVeUEiLCJwaG9uZUlkIjoiMDU0ZTlhYTMtMWNkOC00ZWE4LTllNjAtZDU1NzhjYTlmMWMzIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjFKU0VxY1BjMG52dkdORzRPRGpvaVZHOFJCaz0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJyeW9SY0hYSE9yZmlCNit6QUUxQnIyVWdpUVk9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiQjROS1o4Q1giLCJtZSI6eyJpZCI6IjI1NDEwNDI0NTY1OToyNUBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiIyNTQxMDQyNDU2NTkifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0wrT2s4Y0hFT0NNdjdVR0dBZ2dBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6Ik5VQ1F1VE5KNGRSclNZWEdFQ2xVOUl4b1RUekM0ZXJaN2VIbi9rb0IvUkk9IiwiYWNjb3VudFNpZ25hdHVyZSI6ImpsczBQY1F3bTBnVTd0VDc0SHpaWmV6S0dUVTE5TkpRYXErMWdEY2JnRTVWVEo3dzBObGIwRnBHU25NcHpTUDROdTdvaWZ6R0pDclVQaUtGb3Z4cER3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiJ1QWhJMGFteXNUUS9QRmRZb0RSUkZiYmVsa3FtZlJqVFVMdGR6bmIwMmdKYkQ5d0Nic3RPYU45cjRWb24xSUw0amNGVEZIK3Iwd0E3eld0NUU2YmRBQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDEwNDI0NTY1OToyNUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJUVkFrTGt6U2VIVWEwbUZ4aEFwVlBTTWFFMDh3dUhxMmUzaDUvNUtBZjBTIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzIyNzk1NjI5LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUtJNiJ9';

const prefix = process.env.PREFIX || ',';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'fortunatus';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '254114018035';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DREADED';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'true';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'recording';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'true';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session
};
